name: WordPress CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install and Start MySQL in No-Password Mode
      - name: Start MySQL Service in No-Password Mode
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo service mysql stop
          sudo mysqld_safe --skip-grant-tables --skip-networking &
          sleep 5
          sudo mysql -e "FLUSH PRIVILEGES;"
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '';"
          sudo service mysql restart

      # Step 3: Verify MySQL Service
      - name: Verify MySQL Service
        run: |
          sudo mysql -u root -e "SHOW DATABASES;"

      # Step 4: Create WordPress Database
      - name: Set up WordPress Database
        run: |
          sudo mysql -u root -e "CREATE DATABASE wordpress;"

      # Step 5: Install PHP and Dependencies
      - name: Install PHP and dependencies
        run: |
          sudo apt-get install -y php php-mysql unzip curl

      # Step 6: Download and Set up WordPress
      - name: Set up WordPress
        run: |
          curl -O https://wordpress.org/latest.tar.gz
          tar -xzf latest.tar.gz
          mv wordpress/* .
          cp wp-config-sample.php wp-config.php
          sed -i "s/database_name_here/wordpress/" wp-config.php
          sed -i "s/username_here/root/" wp-config.php
          sed -i "s/password_here//" wp-config.php
          php -S 127.0.0.1:8080 &

      # Step 7: Wait for WordPress to be Ready
      - name: Wait for WordPress Setup
        run: |
          for i in {1..10}; do
            curl -s http://127.0.0.1:8080/wp-admin/install.php && break
            sleep 5
          done

  run-tests:
    runs-on: ubuntu-latest
    needs: setup-environment

    steps:
      # Step 8: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 9: Install Node.js for Cypress
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 10: Install Cypress
      - name: Install Cypress
        run: |
          npm install cypress

      # Step 11: Run Cypress Tests
      - name: Run Cypress Tests
        run: |
          npx cypress run --spec cypress/e2e/login_spec.cy.js
