name: WordPress CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install and Configure MySQL
      - name: Install and Configure MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo service mysql start
          # Set up the root user with no password
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';"
          sudo mysql -e "FLUSH PRIVILEGES;"
          # Create the WordPress database
          sudo mysql -e "CREATE DATABASE wordpress;"
          # Create and configure the runner user
          sudo mysql -e "CREATE USER 'runner'@'localhost' IDENTIFIED BY 'runner_password';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON wordpress.* TO 'runner'@'localhost';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      # Step 3: Verify MySQL Service
      - name: Verify MySQL Setup
        run: |
          sudo mysql -u runner -prunner_password -e "SHOW DATABASES;"

      # Step 4: Install PHP and Dependencies
      - name: Install PHP and dependencies
        run: |
          sudo apt-get install -y php php-mysql unzip curl

      # Step 5: Download and Configure WordPress
      - name: Set up WordPress
        run: |
          curl -O https://wordpress.org/latest.tar.gz
          tar -xzf latest.tar.gz
          mv wordpress/* .
          cp wp-config-sample.php wp-config.php
          sed -i "s/database_name_here/wordpress/" wp-config.php
          sed -i "s/username_here/runner/" wp-config.php
          sed -i "s/password_here/runner_password/" wp-config.php
          php -S 127.0.0.1:8080 &

      # Step 6: Wait for WordPress to be Ready
      - name: Wait for WordPress Setup
        run: |
          for i in {1..10}; do
            curl -s http://127.0.0.1:8080/wp-admin/install.php && break
            sleep 5
          done

  run-tests:
    runs-on: ubuntu-latest
    needs: setup-environment

    steps:
      # Step 7: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 8: Install Node.js for Cypress
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 9: Install Cypress
      - name: Install Cypress
        run: |
          npm install cypress

      # Step 10: Run Cypress Tests
      - name: Run Cypress Tests
        run: |
          npx cypress run --spec cypress/e2e/login_spec.cy.js
